### ISSUE TITLE
Using OpenSSL violates GPL licence

### ISSUE THREAD

**Issue by EionRobb** [seishun/SteamPP#1]
Not very classy deleting the other issue and renaming the title of this issue to something stupid.

It's a genuine issue that you're using OpenSSL with a libpurple plugin.  The fix is to use gnutls or libnss or another GPL-compatible library

**Comment by seishun** [comment]
gnutls and libnss have terrible documentation and I don't consider this a priority issue anyway. If you would like to submit a pull request, then be my guest.

**Comment by seishun** [comment]
Could you now please restore the wiki link? (if I do it myself, it will look like an edit war)

**Comment by EionRobb** [comment]
https://developer.pidgin.im/wiki/ThirdPartyPlugins?action=diff&version=448

Thanks for fixing the plugin :)
