### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by ka223** [seishun/SteamPP#10]
I tried to compile a plugin for pidgin, but I'm stuck at:

"SteamPP-purple-v6$ make steam
make[3]: **\* Keine Regel vorhanden, um das Target »/Resources/Protobufs/steamclient/encrypted_app_ticket.proto«,
benötigt von »encrypted_app_ticket.pb.cc«, zu erstellen. Schluss.
make[2]: **\* [CMakeFiles/steam++.dir/all] Fehler 2
make[1]: **\* [CMakeFiles/steam.dir/rule] Fehler 2
make: **\* [steam] Fehler 2 "

/Resources/Protobufs/steamclient/encrypted_app_ticket.proto
is a path from root directory, that could not be correct?

**Comment by seishun** [comment]
Did you set the `STEAMKIT` cache variable to your SteamKit directory?

**Comment by ka223** [comment]
I unzipped this https://github.com/SteamRE/SteamKit/archive/SteamKit_1.5.0.tar.gz to a sub folder and set "STEAMKIT=./SteamKit-SteamKit_1.5.0/".

**Comment by seishun** [comment]
That's an environment variable. See [this](http://www.cmake.org/Wiki/CMake_FAQ#I_set_a_cmake_variable_in_my_environment.2C_but_it_didn.27t_change_anything._Why.3F).

**Comment by ka223** [comment]
ok, thanks
I tried to compile this at my arm netbook with ubuntu 13.04.

http://www.xup.in/dl,14449353/16095paste.txt/

LIBUV is installed, but some root folder is missing?

Screenshot is not uploading here... 
http://www.xup.in/dl,39505267/2013-12-15-141927_1024x600_scrot_.png/

**Comment by seishun** [comment]
It would help if you set your language to English and placed the output in a code block, since it's barely understandable as it is. If Google Translate has any merit, you got an internal compiler error, which should be reported to the GCC team.

Also, you don't need libuv to build steampurple.
