### ISSUE TITLE
Having issues compiling steamuv

### ISSUE THREAD

**Issue by SebastienGautier** [seishun/SteamPP#11]
Hello,

I can't get Steamuv compiled but Steampurple is compiling perfectly.

``` bash
/home/groseb/Documents/SteamPP/build> make
[ 81%] Built target steam++
[ 90%] Built target steam
[100%] Building CXX object CMakeFiles/steamuv.dir/steamuv.cpp.o
Linking CXX executable steamuv
/usr/bin/ld: libsteam++.a(steammessages_clientserver.pb.cc.o): undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [steamuv] Error 1
make[1]: *** [CMakeFiles/steamuv.dir/all] Error 2
make: *** [all] Error 2
*** Failure: Exit code 2 ***
```

I'm compiling with cmake using KDevelop (Xubuntu 13.04).

**Comment by seishun** [comment]
That's weird, why would steammessages_clientserver.pb.cc have a reference to pthread? Which version of protobuf are you using?

**Comment by SebastienGautier** [comment]
I'm using protobuf 2.4.1 installed with libprotobuf-dev.

**Comment by SebastienGautier** [comment]
I updated to protobuf 2.5.0 but I get the exact same error :/
Edit : It doesn't compile with the newest version, I was using cache files : switching back to 2.4.1

**Comment by seishun** [comment]
Try running CMake with -DCMAKE_EXE_LINKER_FLAGS="-Wl,--copy-dt-needed-entries"

**Comment by SebastienGautier** [comment]
It works perfectly !
I used your method by editing CMakeLists.txt and adding

``` bash
set(CMAKE_EXE_LINKER_FLAGS "-Wl,--copy-dt-needed-entries")
```

Thank you !
