### ISSUE TITLE
Releases v4, v5, v6 don't work with a brand new pidgin

### ISSUE THREAD

**Issue by watergad** [seishun/SteamPP#12]
Releases v4, v5, v6 (binaries) don't work with a brand new pidgin instance.
v3 does.
What am I doing wrong? Do I miss any libraries or something?

**Comment by seishun** [comment]
What do you mean by a "brand new" instance? Also what's your OS?

**Comment by AshleighAdams** [comment]
I need to compile it for Debian, I don't think the Ubuntu bins are compatible with Debian (I think it's because libpurple is old on Ubuntu, or at least the machine it was built on).

**Comment by watergad** [comment]
Sorry, windows.
Brand new = downloaded and reinstalled into empty folder clean latest pidgin, only 1 plugin (SteamPP) added.
There's no steam protocol at the account creation.
v3 appears normally by just adding dll to plugins folder.

**Comment by seishun** [comment]
I don't see any commits between v3 and v4 that could break something. Could you take a look at the debug log (`pidgin -d`) and see if it mentions anything related to steam?

**Comment by watergad** [comment]
(20:00:05) plugins: D:\Users\Watergad\Soft\Pidgin\plugins\libsteam.dll is not loadable: `D:\Users\Watergad\Soft\Pidgin\plugins\libsteam.dll': Не найдена указанная процедура.
I assume you have no problem with russian text?
[ The specified procedure could not be found. ]

(20:04:25) plugins: D:\Users\Watergad\Soft\Pidgin\plugins\perl.dll is not loadable: `D:\Users\Watergad\Soft\Pidgin\plugins\perl.dll': Не найден указанный модуль.
I suppose it's kind of "normal".

(20:04:25) account: Invalid status ID 'available' for account unlucky_ru (prpl-seishun-steam)
......
Doesn't matter because the module is not loaded, I presume.

Windows XP Pro SP 3 ru
VC runtime 2005, 2008, 2010, VS installed.

Different compilers for v3 and v4 maybe?

**Comment by watergad** [comment]
So,
Windows 7 x64, latest pidgin and v6 SteamPP - works fine.
Windows XP Home SP3, latest pidgin and v3 - works, v6 - does not work.
Windows XP Pro SP3, latest pidgin and v3 - works, v6 - does not work.
Most likely is OS-related issue.

**Comment by seishun** [comment]
Could you use [dependency walker](http://www.dependencywalker.com/) on the dll and tell me which dependencies are missing?

**Comment by watergad** [comment]
Libsteam v3: http://i.imgur.com/fU0ZjuA.jpg
Libsteam v4: http://i.imgur.com/a5dAW6Z.jpg

**Comment by seishun** [comment]
Is that on Windows 7 or Windows XP?

**Comment by watergad** [comment]
Windows XP

**Comment by watergad** [comment]
http://i.imgur.com/FNVGR8C.jpg
Windows 7
v3 and v4 are the same

**Comment by seishun** [comment]
Well, it wasn't a missing module anyway, but rather a missing function.

In your v4 screenshot from XP I see that MSVCRT.DLL is marked with a warning. Could you take a look at its or its parent's function list and see if there are any functions that are marked as unresolved?

**Comment by watergad** [comment]
I'm not sure how to do it, is this enough? That's the only one I've found.
http://i.imgur.com/cSMVPXg.jpg

**Comment by seishun** [comment]
It seems Windows XP doesn't have memmove_s. I guess your best bet would be to recompile it yourself.

**Comment by watergad** [comment]
Let's just say WinXP is not supported (:
Thanks for the investigation.
