### ISSUE TITLE
"Typing" notification not updating on text deletion in steampurple

### ISSUE THREAD

**Issue by Archenoth** [seishun/SteamPP#13]
Heyas..!

When typing to someone from your friends list on Steam, they can see that you are typing something... Which is good.

But if you delete everything you've typed without sending anything, it will permanently appear as though you are typing from the other side.

This can be fixed by further typing something and sending it.

This happens with Pidgin 2.10.7 on Windows 7 (64-bit) with the [Windows purple-v6 binary here.](https://github.com/seishun/SteamPP/releases/download/purple-v6/libsteam.zip)

**Comment by seishun** [comment]
Steam has a hard-coded delay of 20 seconds before it removes the typing notification, and sometimes it bugs out and never removes it until a message is received.
