### ISSUE TITLE
Assert when decompressing data

### ISSUE THREAD

**Issue by Looooong** [seishun/SteamPP#17]
Right after authentication with email auth code, I get the following assert
`assert(length == size_unzipped);`

The `length` returned by `archive_read_data` is `ARCHIVE_FAILED`

**Comment by seishun** [comment]
Are you using a steampurple binary or something else?

**Comment by Looooong** [comment]
I created custom loop using Boost library

**Comment by Looooong** [comment]
After debuging `libarchive`, I see that the compression uses **deflate**. And, without the `zlib` installed, `libarchive` couldn't handle decompressing.
