### ISSUE TITLE
Attempt to locate existing buddy before creating a new one

### ISSUE THREAD

**Issue by AshleighAdams** [seishun/SteamPP#3]
If you have moved steam buddies into different groups, or merged them with other contacts, when pidgin is restarted the existing buddies don't show, and all the new buddies are back in their original places.

Here is where it needs changing: https://github.com/seishun/SteamPP/blob/d5c63a6596f441d7e7da6cf66e2470abc875bccc/steampurple.cpp#L387

It should look something more like this: https://code.google.com/p/pidgin-opensteamworks/source/browse/trunk/libsteamworks.cpp#1039

**Comment by seishun** [comment]
Quick question. What should happen to a friend in your friend list if they remove you from theirs?

**Comment by AshleighAdams** [comment]
Shouldn't it just remove the buddy our end?  I'm not really sure what else could happen, other than keeping them around, marking them as removed so you can speak to them via "invite to chat".  To be honest though, I would expect it to removed from the buddy list (as would happen in the native Steam application).

**Comment by seishun** [comment]
Could you give the `buddies` branch a try?

**Comment by AshleighAdams** [comment]
After a few minutes of testing, all seems good.

Thank you.
