### ISSUE TITLE
PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND

### ISSUE THREAD

**Issue by CrazyCrab** [seishun/SteamPP#5]
I can't build SteamPP.
First I use cmake-gui, set the path for steamkit, it outputs this:

```
Could NOT find Libuv (missing:  LIBUV_LIBRARY LIBUV_INCLUDE_DIR) 
Configuring done
Generating done
```

Then I do make steam and get this:

```
$ LC_ALL=C make steam
[ 10%] Running C++ protocol buffer compiler on         /home/%my username%/SteamPP/SteamKit/Resources/Protobufs/steamclient/encrypted_app_ticket.proto
make[3]: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND: Command not found
make[3]: *** [encrypted_app_ticket.pb.cc] Error 127
make[2]: *** [CMakeFiles/steam++.dir/all] Error 2
make[1]: *** [CMakeFiles/steam.dir/rule] Error 2
make: *** [steam] Error 2
```

**Comment by seishun** [comment]
Do you have protoc in your PATH?

**Comment by CrazyCrab** [comment]
I am using debian wheezy and I have libprotobuf-dev installed but I don't have protoc in my path.

**Comment by seishun** [comment]
Never had problems with protoc, I guess it's preinstalled on Ubuntu. I'll add a note to the readme.

**Comment by seishun** [comment]
Does installing protobuf-compiler fix it for you?

**Comment by CrazyCrab** [comment]
Yes, it did. Thank you.

**Comment by m-shimizu** [comment]
Thank you very much!! 
I was rescued, too!

**Comment by sinaaghli** [comment]
Me too, thanks
