### ISSUE TITLE
Feature request: show the game your contact is playing

### ISSUE THREAD

**Issue by CrazyCrab** [seishun/SteamPP#6]
I would be nice to see "%contactname% is playing Dota 2" as a status or something.

**Comment by seishun** [comment]
How exactly would it be displayed? Is there another prpl that does anything similar?

**Comment by CrazyCrab** [comment]
Variant 1:
When someone is offline, you can see "offline" under his name (not sure if it's possible)
![variant1](https://f.cloud.github.com/assets/1116861/1272260/599f3454-2d2b-11e3-98ca-c4bf56ada425.png)

Variant 2:
In this popup that appears when you hold cursor over a contact
![variant2](https://f.cloud.github.com/assets/1116861/1272284/baa28bb6-2d2b-11e3-91e6-f93b7f3db40d.png)
